### ISSUE TITLE
客户端如何配置？

### ISSUE THREAD

**Issue by FenchD** [Kaze1027/overwall-examples#1]
谢谢大佬，请问这种情况是naive流量通过socks转v2ray对吧？这种情况下客户端该怎么配置呢？是需要先用naive客户端链接，再跑v2rayN或qv2ray之类的吗？能请大佬也补充一下详细步骤吗？感激不尽

**Comment by Kaze1027** [comment]
客户端对于后端的xray无感知，说白了流量到达naiveproxy服务器端的caddy之后就完成连接了，后续的就和过墙协议没有关系了，对于客户端来说这和普通naiveproxy没有任何区别，你后面套无数个其他协议都无所谓。客户端Windows用v2rayN即可，现在v2rayN已经支持naiveproxy了。

**Comment by FenchD** [comment]
谢谢大佬。之前没有理解v2ray的inbound可以用socks，我以为只能vmess/vless。还想请问一下大佬，为什么不用naive发v2ray以后，让v2ray根据geosite分流，如果是netflix就自动走落地机，如果其他流量直接outbound？这样省的切换客户端的用户名或者链接域名了。

**Comment by Kaze1027** [comment]
在naiveproxy里面使用不同用户名是为了区分用户等级，因为有时候我并不希望所有人都能够看奈飞，这样我奈飞流量不够用，因此用naive账号来直接划分是否能够访问奈飞落地鸡是比较方便的。还有另一个原因就是当客户端的流量到caddy之后就分不出来了，我还不知道怎么来区分，好像是因为forward proxy的ip匿名化的原因，流量到达xray的时候没办法区分是谁发送来的，如果可以区分，倒是可以在xray上进行根据用户进行分流，也方便统计流量

**Comment by FenchD** [comment]
真心感谢大佬。按这个思路初步搞定了。最后再请教一个问题，全配好以后可以连通，但是caddy会有报错，客户端用的是shadowrocket走的http2，大佬有见过这错误吗？ 报错信息：2023/03/15 01:43:59.850	ERROR	http.log.error	client disconnected	{"request": {"remote_ip": "xx.xx.xx.xx", "remote_port": "63489", "proto": "HTTP/2.0", "method": "CONNECT", "host": "sic.33across.com:443", "uri": "sic.33across.com:443", "headers": {"Proxy-Authorization": [], "Accept-Encoding": ["identity"], "User-Agent": ["nghttp2/1.39.2"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "www.abc.com"}}, "duration": 230.534161442}

**Comment by Kaze1027** [comment]
类似报错我也有，但是太菜了我没找到原因

**Comment by FenchD** [comment]
大佬千万别这么说，我还是学到很多，再次感谢
